### ISSUE TITLE
/multikanban-api/web/stats not found

### ISSUE THREAD

**Issue by Kickball** [mezod/multikanban-api#1]
I followed the steps on multikanban's [wiki](https://github.com/mezod/multikanban/wiki/Gettings-Started).

And when I try to load up the front end for multikanban the following happens:
- multikanban-api/web/stats throws a 404 as it doesn't exist
- multikanban-api/web/ throws the following error 

`{"detail":"No route found for \u0022GET \/\u0022 (from \u0022http:\/\/kanban.DOMAIN.TLD\/multikanban-api\/\u0022)","status":404,"type":"about:blank","title":"Not Found"}`

Any help?

Thanks,
Kickball

**Comment by mezod** [comment]
It is certainly a path issue. Where is kanban.domain.tld pointing to?

In my local version: http://localhost:8888/multikanban-api/web/stats returns
{
"numberUsers": 36,
"numberKanbans": 36,
"numberTasks": 169,
"numberCompletedTasks": 35
}

How does your folder structure look like with the two projects?

Check if what I do here helps you somehow: http://blog.joanboixados.com/deploying-multikanban/

**Comment by mezod** [comment]
I can send you the postman collection for the api requests if you wish to try it out separately before connecting it with the app. let me know!

**Comment by Kickball** [comment]
The kanban.domain.tld would take you to the /var/www/html folder and it would by default load the index.[php|html] in that folder.

Maybe I've not got the multikanban-api folder in the right place.

[This](https://paste.ee/p/cYylQ) is my overall folder structure, sort of a dump post I can try to narrow it down if you have a specific area you need to me to look at.

I saw your blog post, and it is linked at the bottom of the wiki.

The last problem which I've found is that this repo doesn't have a /web/stats, the [directory](https://github.com/mezod/multikanban-api/tree/master/web) only has an index.php

New to this kind of thing so I'm not really sure what a postman collection is, but if it is documentation of some sort I wouldn't mind looking at it.

Thanks,
Kickball

**Comment by mezod** [comment]
This is where the routes are defined: https://github.com/mezod/multikanban-api/blob/master/src/multikanban/multikanban/Controller/StatsController.php

But don't worry about that, it's not the problem. The problem is that the js app has relative paths to the API calls. But apparently, the API is actually responding, just that with an error that shouldn't be there. Have you tried to make a request to the API without using the js app? i.e putting http://kanban.domain.tld/multikanban-api/web/stats and see if it returns the same error? I'll be back home later tonight and I'll hopefully have more time to look into this!

**Comment by Kickball** [comment]
http://kanban.domain.tld/multikanban-api/web/stats throws a 404.

I might be missing some information but I am not sure how the /web/stats file is generated, it is not in the [repo](https://github.com/mezod/multikanban-api/tree/master/web) itself.

Also am I meant to have configured:
- Sequel Pro
- Silex
- CORS
- The baseUrl
- Virtual Hosts

**Comment by Kickball** [comment]
I've not been able to resolve this issue.
